### ISSUE TITLE
Can't get extensions to function after updating rxvt-unicode to 9.26

### ISSUE THREAD

**Issue by mokkurkalve** [muennich/urxvt-perls#100]
There's little I can say. These extensions used to work for me but today I updated rxvt-unicode 9.22 => 9.26 and they stopped working.

**Comment by arcolinuxz** [comment]
same here...

**Comment by megnu** [comment]
Anyone know a solution? Would be greatly appreciated

**Comment by mokkurkalve** [comment]
I'm starting to wonder if the extensions do work and it's the keyboard command to activate them that broke for me in the upgrade to 9.26.
I can't get any command given in .Xdefaults in the form like
```
URxvt*keysym.M-u: perl:url-select:select_next
```
to work anymore after the upgrade rxvt-unicode 9.22 => 9.26.
However I can't figure out any more or find anything on the internet that is helpful, so I'm pretty stuck here.

**Comment by Aquassaut** [comment]
Same here. Has anyone found a solution ?

**Comment by megnu** [comment]
I've rolled back to perl v5.32.1 / rxvt-unicode v9.22 for a temporary solution

**Comment by mokkurkalve** [comment]
I seem to have found a solution. For the "keysym" in .Xdefaults this form must be used:
```
URxvt.keysym.M-u: url-select:select_next
```
The old form of the asterisk must be replaced by a single dot it seems. And the use of "perl:" are deprecated.

**Comment by megnu** [comment]
Thanks a lot, now it's working for me. I just had to replace those asterisks and remove the `perl:` from my .Xresources :)

**Comment by arcolinuxz** [comment]
I can confirm that changing the * into a . is the solution.

I have changed all * into . and it works.

Currrent Xresources is here
https://github.com/arcolinux/arcolinux-root/blob/master/etc/skel/.Xresources

More info
https://youtu.be/WCa6aae2bRY

I think we can close this one.

**Comment by mokkurkalve** [comment]
Yeah. Noting wrong with this package, except maybe it needs a bit of refreshing on the documentation regarding urxvt 9.26. But that's not in the scope of this report.
