### ISSUE TITLE
Yanking in keyboard-select and url-select is only to PRIMARY selection

### ISSUE THREAD

**Issue by anderspapitto** [muennich/urxvt-perls#39]
There should be an option to also copy to the CLIPBOARD selection - possibly by just calling into the `copy` function of the `clipboard` extension.

**Comment by Konfekt** [comment]
That makes me wonder: Why an extension to copy text from the terminal by the keyboard, for afterwards having to paste it by the middle mouse button ? How come pasting it, say by `Ctrl+V` instead would not be useful to you?

**Comment by muennich** [comment]
I'm using `Shift-Insert` to paste from the PRIMARY.
