### ISSUE TITLE
keyboard-select yank to Clipboard buffer 

### ISSUE THREAD

**Issue by Konfekt** [muennich/urxvt-perls#57]
Hello, 

I am using openSuse 13.2 with KDE and klipper. The yank command of the keyboard-select extension  does not make the yanked text available immediately for pasting by `ctrl-v` but instead it appears only in the yank history of klipper. Now I learned that there are three clipboards under xorg by

http://unix.stackexchange.com/questions/82311/how-to-make-shiftinsert-paste-selection-after-closing-window-with-selection/82326#82326

Would sending the yanked text to the CLIPBOARD clipboard instead of the PRIMARY clipboard resolve this?
As far as I can tell, there are no options in Klipper to unify with the PRIMARY clipboard.

**Comment by muennich** [comment]
Sigh. Dup of #39, #52, #53, #55.

**Comment by Konfekt** [comment]
Could you explain why it defaults to PRIMARY instead of CLIPBOARD then?  Is this as question of Shift-Insert  to paste from primary being more easily reachable than Ctrl-V to paste from Clipboard?

You also say at https://github.com/muennich/urxvt-perls/issues/52 that since version 9.20 rxvt-unicode has builtin clipboard support. What does this change for the yank command in keyboard-select?

**Comment by muennich** [comment]
It uses the PRIMARY buffer because the API does not make the CLIPBOARD buffer accessible. The new clipboard support does only render the clipboard extension obsolete.

**Comment by Konfekt** [comment]
Ok, that's a valid reason. 

Because in principle Klipper keeps track of PRIMARY it's a Klipper issue after all (I forgot to explain Klipper though: It is a clipboard manager under KDE that keeps a history of your recent clipboard pastes): 

The entry is stored in the history at the top but Ctrl-V does not paste it. Seems like an inconsistency of Klipper.
