### ISSUE TITLE
copy/paste fails to work as expected

### ISSUE THREAD

**Issue by GenomeAnalysts** [muennich/urxvt-perls#58]
Current Arch Linux distro running on MacBookPro9,2 (mid-2012), using:
extra/xorg-server 1.16.4-1
community/i3-wm 4.8-3
community/rxvt-unicode 9.21-1
community/urxvt-perls 2.1-1

$ cat .Xresources |grep perl|grep -v ^\!
URxvt.perl-ext-common: default,keyboard-select,clipboard,url-select
URxvt.keysym.M-Escape: perl:keyboard-select:activate
URxvt.keysym.M-s: perl:keyboard-select:search
URxvt.keysym.M-c:   perl:clipboard:copy
URxvt.keysym.M-v:   perl:clipboard:paste
URxvt.keysym.M-C-v: perl:clipboard:paste_escaped
URxvt.keysym.M-u: perl:url-select:select_next

$ cat .xinitrc|grep urxvt
urxvtd -q -o -f

Your documentation from /usr/lib/urxvt/perl/keyboard-select reads in part:
Use Meta-Escape to activate selection mode, then use the following keys:
  h/j/k/l:    Move cursor left/down/up/right (also with arrow keys)
  g/G/0/^/$/H/M/L/f/F/;/,/w/W/b/B/e/E: More vi-like cursor movement keys
  '/'/?:      Start forward/backward search
  n/N:        Repeat last search, N: in reverse direction
  Ctrl-f/b:   Scroll down/up one screen
  Ctrl-d/u:   Scroll down/up half a screen
  v/V/Ctrl-v: Toggle normal/linewise/blockwise selection
  y/Return:   Copy selection to primary buffer, Return: deactivate afterwards
  q/Escape:   Deactivate keyboard selection mode

and documentation in /usr/lib/urxvt/perl/clipboard reads in part:
The use of the functions should be self-explanatory!

and indeed, this is pretty clear to me:
URxvt.keysym.M-c:   perl:clipboard:copy
URxvt.keysym.M-v:   perl:clipboard:paste
...and gives me the impression that your code should be copying to the CLIPBOARD buffer in X, not the PRIMARY buffer.

Everything described in the docs seems to work for me except the following key-combination:
"M-c" (I know that's Meta-c or in my case, alt/option-c)

In attempting to use these tools, I carefully used the following 4 procedures:

1a) modify .Xresources;
2a) run "$ #xrdb ~/.Xresources" to reload modified .Xresources;
3a) $mod-Return (an i3 key combination; it spawns a new urxvtc for me);
4a) in new urxvtc, generate some text in the terminal;
5a) "M-Escape" (terminal feedback: "Bot" highlighted in yellow at bottom right of terminal);
6a) multiple presses of "k" and "h" to position cursor;
7a) "v" to toggle normal selection mode (terminal feedback: "-V- Bot" highlighted in yellow);
8a) multiple presses of "l" (lowercase L) to highlight text desired for selection (terminal feedback: background/foreground colors reversed for selected text);
9a) "M-c" to attempt to copy selection to CLIPBOARD buffer (terminal feedback: none visible)
10a) "Escape" to deactivate keyboard selection mode (terminal feedback: "-V- Bot" disappears)
11a) "M-v" to attempt to paste this copied CLIPBOARD buffer content to the terminal (terminal feedback: not the most-recently-attempted copied text, but the previous-to-that-copied-text from using firefox with mouse-selected text followed by "C-c" is pasted into terminal)

I've also tried steps 1a-9a above followed by:
10b) "Return" to copy selection to primary buffer, Return: deactivate afterwards
11b) "two-finger-tap" on synaptics touchpad (desired copied text is pasted to destination)

And I've also tried steps 1a-9a above followed by:
10c) "y" to copy selection to primary buffer (terminal feedback: reversed color selection returns to normal)
11c) "q" to deactivate keyboard selection mode (terminal feedback: "-V- Bot" disappears)
12c) "two-finger-tap" on synaptics touchpad (desired copied text is pasted to destination)

And I tried steps 1a-10a above followed by:
11d) "two-finger-tap" on synaptics touchpad (desired copied text is NOT pasted to destination)

Both procedures b and c work fine, I think because "y" and "Return" copy the selection to the PRIMARY buffer rather than the CLIPBOARD buffer. But I get the impression from your documentation and from the filename itself (/usr/lib/urxvt/perl/clipboard) that "M-c" should be copying the selected text to the CLIPBOARD buffer, not the PRIMARY buffer in X. Just to make sure I wasn't interpreting your documentation incorrectly, I tried procedure d, and again got behavior different than I expected.

I noticed your additional words:

You can also overwrite the system commands to use for copying/pasting.
The default ones are:
  URxvt.clipboard.copycmd:  xsel -ib
  URxvt.clipboard.pastecmd: xsel -ob

So I added these lines to .Xresources:
URxvt.clipboard.copycmd:  xsel -ib
URxvt.clipboard.pastecmd: xsel -ob

and still don't get selected text copied to the CLIPBOARD buffer.

$ xsel -ob
from the command-line works as expected when I precede that command by selecting text in firefox with the mouse and then copy it to the X CLIPBOARD buffer using "C-c".

So is this a bug/issue? Or are my expections wrong? Perhaps I'm interpreting your documentation about the use and function of "M-c" in the clipboard script incorrectly. Any thoughts on what's going on here?

**Comment by muennich** [comment]
keyboard-select does not copy the selected text to the `PRIMARY` until you use `y` or `Return`. The clipboard extension copies the contents of the `PRIMARY` buffer to the `CLIPBOARD` buffer, not the text currently selected with keyboard-select.

**Comment by GenomeAnalysts** [comment]
OOOoooohhhh!!! Now I understand!

But... I don't see that mentioned anywhere in your documentation. Did I miss it somewhere? My apologies if I missed it.

I think these perl scripts are TERRIFIC! But I spent HOURS trying to solve this problem because I didn't understand that M-c copies the PRIMARY buffer to the CLIPBOARD buffer. So I didn't understand that getting something into the CLIPBOARD buffer was a two step process (at least, without the autocopy feature turned off) after selecting the text: (1) copy the selection into the PRIMARY buffer with y or Return, (2) copy the PRIMARY buffer into the CLIPBOARD buffer with M-c.

Thanks for explaining, but I think a lot more people would be just as excited about your package if you made that explicitly clear in your documentation. Just a thought.
