### ISSUE TITLE
[RFE] Add yy command

### ISSUE THREAD

**Issue by memeplex** [muennich/urxvt-perls#62]
It would be useful to copy the current line to the clipboard efficiently as it is a frequent operation.

**Comment by muennich** [comment]
keyboard-select does only have vi-like key-bindings, it is not really modal. Using `Y` would be possible, but all of the `yy`, `yj` or `3yj` are not possible.

**Comment by memeplex** [comment]
`Y` will be ok as vi(m) is already inconsistent in its definition: it's the same as `yy`.

That said, the most common use case I found for "yank line" is to copy the current line (say you're in the interactive shell of your favourite language) to an editor. Maybe a direct shortcut similar to `keyboard-select:search` will fit the bill also (or even better).

**Comment by muennich** [comment]
Does your shell not offer this feature directly? For instance, bash has `edit-and-execute-command` (C-x C-e) and zsh `edit-command-line` in zshcontrib.

**Comment by memeplex** [comment]
Yes, it does. But there are other use cases. Mainly, you're in an interpreter shell, say ipython, and exploratory build some complex line that you want to copy to your editor, which is already open in some other window.

**Comment by muennich** [comment]
Sorry that it took so long to find some time to add this. Enjoy!

**Comment by memeplex** [comment]
Thanks :)
