### ISSUE TITLE
 URxvt.clipboard.autocopy and block selections

### ISSUE THREAD

**Issue by memeplex** [muennich/urxvt-perls#64]
Yanking normal or line selections updates both the primary selection and the clipboard when autocopy is on. But block selections yanks updates only the primary selection, despite the value of autocopy. This is pretty strange.

**Comment by muennich** [comment]
This should be fixed with commit 537f2df. Sorry for answering/fixing this so late.

**Comment by memeplex** [comment]
Thank you!
