### ISSUE TITLE
url-select only highlighting part of a link

### ISSUE THREAD

**Issue by esn89** [muennich/urxvt-perls#66]
Here is an example of what I mean:

http://i.imgur.com/9yrPSuJ.png

I am running debian on rxvt-unicode-256color
Is anyone else experiencing this issue?

**Comment by muennich** [comment]
Do you use the default URL regexp?

**Comment by esn89** [comment]
I am not too sure what that is, how can I find out if I am using that (or have it turned on)?

**Comment by muennich** [comment]
Do you have any lines setting a `matcher.pattern` in your `~/.Xdefaults` or `~/.Xresources`?

**Comment by esn89** [comment]
Ahh, no.  I do not have any of those in my Xdefaults or Xresources.

**Comment by Fraterius** [comment]
I've got the same problem with such url:

http://release24.pl/wpis/45532/%22Xenia%22+(2014)+LIMITED.DVDRip.x264-BiPOLAR++

the selected part is:

http://release24.pl/wpis/45532/%22Xenia%22+(2014)+LIMITED

**Comment by muennich** [comment]
What happens when you actually copy such partially selected URL? Is the copied text the same as the highlighted one? I am trying to find out if the problem lies in matching or rendering.

**Comment by esn89** [comment]
What happens for me if I actually copy such a partially selected URL is that the copied text is exactly the same as the highlighted one.  Meaning it is truncated.

**Comment by muennich** [comment]
I've just deprecated the `url-select` extension in favor of the `matcher` extension shipped with rxvt-unicode version 9.21. As such I'm not going to look into this further, sorry.

**Comment by esn89** [comment]
@muennich , 

Gotcha.  Thanks for taking your time to look into it in the first place, it is appreciated.
