### ISSUE TITLE
Feature Request : open urls of images with image viewer

### ISSUE THREAD

**Issue by Buridan** [muennich/urxvt-perls#67]
hi,

Thanks for your work which've made my CLI sessions even more accurate.

I wonder if the url catcher can understand the difference between misc links and image links.
When there is an image link, the behavior of the url catcher could be to delegate the opening of the link to an image viewer.

Regards,
Buridan

**Comment by muennich** [comment]
The matcher plugin can do this via its `URxvt.matcher.pattern.X` and `URxvt.matcher.launcher.X` resource settings.

**Comment by antoszka** [comment]
Tako rzecze Paul-emmanuel LETT (2015-11-14, 06:26):

> I wonder if the url catcher can understand the difference between misc links and image links.
> When there is an image link, the behavior of the url catcher could be to delegate the opening of the link to an image viewer.

For that you can employ a custom ${BROWSER} in the form of a dispatcher script
that uses certain browsers/apps for certain url based on whatever criteria you
wish.

I have something very simple along these lines:

#!/bin/bash
URL=$1

if [[ $URL =~ http.*youtu\.*be.* ]]; then 
    mpv $URL
elif [[ $URL =~ http.*vimeo.* ]]; then
    mpv $(youtube-dl -g $URL)
elif [[ $URL =~ .*(mp[34]|ogg|avi|webm)$ ]]; then
    mpv $URL
elif [[ $URL =~ plus\.google\.com ]]; then
    /usr/bin/google-chrome-stable $URL
elif [[ $URL =~ groups\.google\.com ]]; then
    /usr/bin/google-chrome-stable $URL
elif [[ $URL =~ goo\.gl ]]; then
    /usr/bin/google-chrome-stable $URL
else
    #dwb $URL
    #vivaldi $URL
    #chromium $URL
    #opera -newtab $URL
    #seamonkey-bin $URL
    firefox-bin -new-tab $URL
    #qutebrowser $URL
fi

**Comment by Buridan** [comment]
It works, thanks
