### ISSUE TITLE
highlightColor not honored

### ISSUE THREAD

**Issue by memeplex** [muennich/urxvt-perls#69]
The selections of urxvt-perls always use inverted fg/bg colors for the highlight, no matter what the value of the highlightColor resource is. The builtin mouse selection of urxvt does honour this setting, though.

I'm not sure whether this is a defect in the perl api or in urxvt-perls itself. There is `urxvt::SET_COLOR` that may help.

**Comment by muennich** [comment]
I do not have the time for this, sorry. Also, none of the extensions shipped with rxvt-unicode seem to make use of this resource setting.

**Comment by memeplex** [comment]
Ok, I'm giving it a look. The selection extension seems to work fine.

**Comment by memeplex** [comment]
It seems like a bug in `selection_make` to me. I've reported it upstream.

**Comment by muennich** [comment]
Just to clarify things: keyboard-select and url-select do their own drawing (in reverse video) while selecting text. `selection_make` is only used to copy the corresponding text. The builtin matcher extension also uses reverse-video when selecting URLs with the `matcher:select` action and does not honour the `highlightColor` resource setting.

**Comment by memeplex** [comment]
Ahh... ok, I'll keep looking at this, then, my perl is very poor (I was a perl programmer once, about 15 years ago).

**Comment by memeplex** [comment]
Well, I see no simple way of doing this from the perl api. You can just xor some bits of a rendition (as you did) or you can create an overlay with a full rendition, but the overlay is not "transparent" so you will have to rewrite the selected text on top of it. I will ask in the urxvt mailing list, anyway.

**Comment by muennich** [comment]
You can use `ROW_r` to get the rendition bits of a line, then use `urxvt::SET_COLOR` (as you've already mentioned) or `urxvt::SET_BGCOLOR` to alter the selected cells in the returned rendition array and then use `ROW_r` again to set the new rendition.

**Comment by memeplex** [comment]
Thank you very much. Could you help me a bit with this:

```
sub highlight {
        my ($self, $br, $bc, $er, $ec) = @_;
        for (my $r = $br; $r <= $er; $r++) {
                my @rend = map { urxvt::SET_COLOR($_, '#ffffff', '#ffffff') } $self->ROW_r($r);
                $self->ROW_r($r, \@rend);
        }
}
```

I'm trying to replace `$self->scr_xor_span($br, $bc, $er, $ec, urxvt::RS_RVid);` by a call to `highlight` above (I know there are many details missing, it's just a (bad) start). In its current state I expect it to paint all rows in range white. But it doesn't. Maybe you could spot the problem in 1% the time it will take to me.

**Comment by memeplex** [comment]
Sorry for my crappy perl, I'm relearning about dereferencing. Now it seems to work:

```
               my $rend = $self->ROW_r($r);
                my @arend = map { urxvt::SET_COLOR($_, '#ffffff', '#ffffff') } @$rend;
                $self->ROW_r($r, \@arend);
```

**Comment by memeplex** [comment]
Well I give up, just indexed colors seems to be accepted by `SET_COLOR`, so this would defeat the goal of reading the color from x resources.

Thank you very much for your hints and sorry for the noise.

**Comment by memeplex** [comment]
They answered the following in the urxvt mailing list:
 
> Try scr_xor_span with urxvt::RS_Sel.
