### ISSUE TITLE
keyboard-select highlighting breaks when cursor reaches top of terminal

### ISSUE THREAD

**Issue by Evidlo** [muennich/urxvt-perls#70]
Steps to reproduce
-----------------------
 * dmesg (produce some text)
 * Enter keyboard-select `Meta Esc`
 * Enter line selection mode `Shift V`
 * Move cursor to top of terminal
 * Highlighting stops when you continue past this point

All the lines seem to be selecting just fine, as I can yank/paste the entire selection.

Also, when you yank the selected lines with `y`, the upper lines that didn't get highlighted are now highlighted, probably because the script inverts the color of the entire selection.

![](http://i.imgur.com/JwoNjUY.png)
Selecting lines

![](http://i.imgur.com/FYKYpNs.png)
After yank

**Comment by muennich** [comment]
Sorry for the late reaction. Commit e00a109 fixes this for me. Thanks for reporting the issue, especially in such good form.
