### ISSUE TITLE
urxvt doesn't start: handshake key mismatched

### ISSUE THREAD

**Issue by TimorLee** [muennich/urxvt-perls#71]
Hi,
urxvt won't launch anymore on my Archlinux (running testing repos) due to following error:
`./rxvtperl.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xdb80080)`
I can't find any clue how to solve this, so I thought I'd ask the developers ;)

**Comment by muennich** [comment]
This has nothing to do with urxvt-perls but with [rxvt-unicode](http://software.schmorp.de/pkg/rxvt-unicode.html) itself. 
Nevertheless, your problem is, that you do not have the same version of perl installed that your rxvt-unicode was built against.
