### ISSUE TITLE
rebinding clipboard copy/paste keys in urxvt >= 9.20

### ISSUE THREAD

**Issue by Konfekt** [muennich/urxvt-perls#78]
The clipboard extension is not deprecated as it allows to rebind the copy and paste keys. The built-in functionality does not, see http://unix.stackexchange.com/questions/294337/rebinding-ctrl-alt-cv-to-ctrl-shift-cv-in-urxvt-9-20

**Comment by muennich** [comment]
The eval extension shipped with rxvt-unicode has `paste_clipboard` and `selection_to_clipboard` actions for this, that can be bound to any keysym.

**Comment by Konfekt** [comment]
Thanks. Posted at http://unix.stackexchange.com/questions/294337/rebinding-ctrl-alt-cv-to-ctrl-shift-cv-in-urxvt-9-20/329556#329556
