### ISSUE TITLE
keyboard select: why not add more obvious key bindings?

### ISSUE THREAD

**Issue by kindaro** [muennich/urxvt-perls#82]
It took a visit to google to figure out that to start to select an area I have to use `v`. This is even though I use vim daily. The more obvious key bindings -- especially for a user coming from a background other than linux -- would be, I believe, `Space` or `Shift` for starting/stopping to select and `Enter` for copying to the buffer. As far as I see, it would not conflict with existing key bindings.

**Comment by muennich** [comment]
It uses vi key-bindings. If you do not like that you're free to fork and change them.

**Comment by kindaro** [comment]
Why not have both vi keys and "layman" keys if they don't intersect?

**Comment by muennich** [comment]
"Layman" key mappings are more like the ones introduced in pull request #68. I'm not a big fan of pleasing everyone and supporting multiple ways for the same thing.

keyboard-select's purpose for me is providing vi-like key bindings for rxvt-unicode's scrollback buffer. I wrote it and thus it has vi-like key bindings. If you do not like this, you can either fork and change them or move on.
