### ISSUE TITLE
perl//matcher not automatically starting different app based-on match

### ISSUE THREAD

**Issue by klopsi** [muennich/urxvt-perls#83]
Hi, trying to set different actions for different url types using perl/matcher and .Xresources
URxvt.matcher.pattern.1: youtube
URxvt.matcher.launcher.0: /usr/bin/palemoon 
URxvt.matcher.launcher.1: /usr/bin/mpv 

Doesn't start a youtube url with mpv.  

What settings could match youtube or youtu.be and launch mpv?

Thanks, cheers.

**Comment by muennich** [comment]
This repo has nothing to do with the matcher plugin; it is shipped with rxvt-unicode.
