### ISSUE TITLE
terminal width being too narrow makes links unyankable

### ISSUE THREAD

**Issue by sorezzz** [muennich/urxvt-perls#85]
https://i.imgur.com/DmQwRIG.png see pic. using arch linux with i3 and rxvt-unicode-patched. thanks a lot.

**Comment by muennich** [comment]
Duplicate of issue #6.

**Comment by Evidlo** [comment]
Can't tell if that's Weechat, but if it is you can use raw mode (Alt-l) to hide all the extra formatting so you can yank it.
