### ISSUE TITLE
Doubts on usage

### ISSUE THREAD

**Issue by tigerjack** [muennich/urxvt-perls#87]
I'm having some problems using your `keyboard-select` perl extension.
I can easily enter the "selection mode" and copy the text but, as said in the script comments, it only copy the selection on the primary buffer. Is there any way to have it on the clipboard?
I've also tried to add the `selection-to-clipboard` to the list of perl extensions, but it doesn't seem to work for me.
The only workaround I've found at the moment is to use `xsel -o -p | xsel -i -b`. Surely I can bind it to a shortcut, but I was wondering if there is a better way.

You can see my `.Xresouces` configuration  [here](https://github.com/tigerjack/dotfiles/blob/master/.Xresources.d/urxvt)
I'm using `rxvt-unicode (urxvt) v9.22` and `urxvt-perls-2.2-1` on Arch Linux.

**Comment by muennich** [comment]
Please have a look at the new `URxvt.keyboard-select.clipboard` X resource.

**Comment by tigerjack** [comment]
Hey @muennich , could you please be more specific? I've tried to add `URxvt.keyboard-select.clipboard:true` to the `.Xresources` configuration, but it doesn't seem to work.

**Comment by muennich** [comment]
You need to install the latest version of keyboard-select from the repo in order to get the `clipboard` resource.
