### ISSUE TITLE
keyboard-select.clipboard ineffective

### ISSUE THREAD

**Issue by funksh0n** [muennich/urxvt-perls#88]
I've added `*keyboard-select.clipboard: true` to my .Xresources file, restarted my x session, but can still only yank to the primary buffer.
I've attempted Ctrl+Shift+v in urxvt which works for other copied content.  I've also tried "+p in neovim, as well as "*p to confirm the selection is in the primary buffer.
url-select also exhibits this behavior, yanking only to the primary buffer.

https://ptpb.pw/KS1H.mp4
![version](https://ptpb.pw/KtL6.png)

**Comment by muennich** [comment]
Version 2.2 does not have the `clipboard` option. It's only in the current master, so you'll need to intall a tarball directly from github or install the `urxvt-perls-git pkg` from the AUR.

**Comment by funksh0n** [comment]
> Hello,
> i came to the same problem that i can't copy to clipboard. After putting the newest keyboard-select script into my ~/.urxvt/ext/ folder, my terminal freezes, when i copy via y or return key and paste the text again.

I took keyboard-select from this repo and added it to ~/.urxvt/ext/ and it worked for me.  You could try removing urxvt-perls and instead install urxvt-perls-git from the aur?

**Comment by zanona** [comment]
Thanks for this @funksh0n I had problems installing the urxvt-perls-git from AUR throwing some errors during installation. Copying the script to `~/.urxvt/ext` worked very well.
