### ISSUE TITLE
A script to support terminal hyperlinks (ESC-code based)

### ISSUE THREAD

**Issue by psprint** [muennich/urxvt-perls#93]
Hi!
There's the recent feature of terminals such as the VTE-based to support HTML-like URLs, see: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

I thought, if you know rxvt and perl well, maybe you could add such support also to rxvt, through a perl extension?

**Comment by muennich** [comment]
Sorry, I do not have time to do this.
